### ISSUE TITLE
Support for QEMU Agent Command

### ISSUE THREAD

**Issue by ca1e** [digitalocean/go-libvirt#155]
Hi! I found there is `QEMUProcDomainAgentCommand = 3` have been defined but have no methods implement, is there any plans? thanks here!

**Comment by ca1e** [comment]
I really want to do some thing like `virsh qemu-agent-command 'commands'` with this repo!

**Comment by connorkuehl** [comment]
Hi @ca1e,

Have you tried using [Libvirt.QEMUDomainAgentCommand](https://pkg.go.dev/github.com/digitalocean/go-libvirt#Libvirt.QEMUDomainAgentCommand)? I think you'd have to handcraft your own QEMU Guest Agent protocol messages in JSON though because I don't know of a Go package that contains implementations of the [QEMU Guest Agent Protocol message types](https://www.qemu.org/docs/master/interop/qemu-ga-ref.html).

**Comment by ca1e** [comment]
omg thank you! I just saw this method for execute agent commands!

**Comment by ca1e** [comment]
omg thank you! I just saw this method for execute agent commands!
