### ISSUE TITLE
is there any way to extract error code?

### ISSUE THREAD

**Issue by liaoishere** [digitalocean/go-libvirt#65]
When calling a RPC method of libvirt, the returned error contains an error code used to indicate the error types, which is helpful.

I found there's no way to extract the error code from method call, cause the error returned in this package only contains the error message, which is not friendly for error cause tracing.

Error handling in this package(https://github.com/digitalocean/go-libvirt/blob/master/rpc.go#L355):
```go
// decodeError extracts an error message from the provider buffer.
func decodeError(buf []byte) error {
    var e libvirtError

    dec := xdr.NewDecoder(bytes.NewReader(buf))
    _, err := dec.Decode(&e)
    if err != nil {
        return err
    }

    if strings.Contains(e.Message, "unknown procedure") {
        return ErrUnsupported
    }

    return errors.New(e.Message)
}
```

As the code above shows, the actual error returned was constructed by only the `e.Message`, `e.Code` was dropped.

I want to write a code to lookup domain first, then compare the error code to determine whether to define a new domain, something like this:

```go
dom, err := l.DomainLookupByName("test")
if err != nil {
    if libvirtError, ok := err.(libvirt.Error); ok {
        if libvirtError.Code == libvirt.ERR_NO_DOMAIN {
            ...
        }
    }
}
```

Is there any plan to support error code extraction?

**Comment by trapgate** [comment]
There isn't a way to get at the error codes today, but we will need to implement something. We have an issue with some discussion about this, but it was closed without any resolution: https://github.com/digitalocean/go-libvirt/issues/56

I'm still reluctant to simply expose all of libvirt's error codes, because there are many of them and most of them aren't useful to clients of the library. But we will need to arrive at some solution for this.
